**Artificial Neural Networks**

Welcome to the last session of the Python and Deep Learning Bootcamp.Now it's time to apply all the knowledge we have gained on Pythonn and Artificial Neural Networks to recognize the hand written digits in an usage.

In [79]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
import numpy as np

**Creating dataset for an And Gate**

In [80]:
x = np.array([[0,0], [0,1], [1,0], [1,1]], "uint8")
y = np.array([[0], [0], [0], [1]], "uint8")

**Creating a sequential model using tensorflow**

In [81]:
model = Sequential()
model.add(Dense(units=1, activation='sigmoid', input_dim=2))  ## MODEL CONTAINS ONLY ONE OUTPUT NEURON
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()


Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 1)                 3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [82]:
model. fit(x, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 327ms/step - loss: 0.7484 - accuracy: 0.7500
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 0.7481 - accuracy: 0.7500
Epoch 3/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7478 - accuracy: 0.7500
Epoch 4/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7475 - accuracy: 0.7500
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7472 - accuracy: 0.7500
Epoch 6/50
1/1 [==============================] - 0s 3ms/step - loss: 0.7469 - accuracy: 0.7500
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7466 - accuracy: 0.7500
Epoch 8/50
1/1 [==============================] - 0s 6ms/step - loss: 0.7463 - accuracy: 0.7500
Epoch 9/50
1/1 [==============================] - 0s 4ms/step - loss: 0.7460 - accuracy: 0.7500
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 0.7457 - accuracy: 0.7500
Epoch 11/50
1/1 [====================

In [83]:
model.fit(x,y,epochs=500)

Epoch 1/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7333 - accuracy: 0.7500
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7330 - accuracy: 0.7500
Epoch 3/500
1/1 [==============================] - 0s 13ms/step - loss: 0.7327 - accuracy: 0.7500
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7324 - accuracy: 0.7500
Epoch 5/500
1/1 [==============================] - 0s 10ms/step - loss: 0.7321 - accuracy: 0.7500
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7318 - accuracy: 0.7500
Epoch 7/500
1/1 [==============================] - 0s 3ms/step - loss: 0.7315 - accuracy: 0.7500
Epoch 8/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7312 - accuracy: 0.7500
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7309 - accuracy: 0.7500
Epoch 10/500
1/1 [==============================] - 0s 9ms/step - loss: 0.7306 - accuracy: 0.7500
Epoch 11/500
1/1 [=========

In [84]:
print(model.layers[0].get_weights())

[array([[ 0.45990378],
       [-0.42151284]], dtype=float32), array([-0.5401394], dtype=float32)]


In [85]:
model.predict(x)

array([[0.36815518],
       [0.27654755],
       [0.47995186],
       [0.37712985]], dtype=float32)

**Creating Database for a XOR gate**

In [86]:
x = [[0,0], [0,1], [1,0], [1,1]]
y = [[0], [1], [1], [0]]

In [89]:
xor = Sequential()
xor.add(Dense(2, input_dim=2, activation= 'sigmoid')) #hidden laer with 2 neurons
xor.add(Dense(1, activation= 'sigmoid')) #output laer with 1 neuron
xor.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
xor.summary()




Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 2)                 6         
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [91]:
xor.fit(x, y, epochs=1000)

Epoch 1/1000
1/1 [==============================] - 0s 374ms/step - loss: 0.7017 - accuracy: 0.5000
Epoch 2/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7016 - accuracy: 0.5000
Epoch 3/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7014 - accuracy: 0.5000
Epoch 4/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7013 - accuracy: 0.5000
Epoch 5/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7011 - accuracy: 0.5000
Epoch 6/1000
1/1 [==============================] - 0s 8ms/step - loss: 0.7009 - accuracy: 0.5000
Epoch 7/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7008 - accuracy: 0.5000
Epoch 8/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7006 - accuracy: 0.5000
Epoch 9/1000
1/1 [==============================] - 0s 4ms/step - loss: 0.7005 - accuracy: 0.5000
Epoch 10/1000
1/1 [==============================] - 0s 5ms/step - loss: 0.7003 - accuracy: 0.5000
Epoch 11/1000
1/1

In [92]:
xor.get_weights()

[array([[ 2.026941 ,  2.1977015],
        [ 2.15541  , -1.6097213]], dtype=float32),
 array([-0.17218913,  1.3011762 ], dtype=float32),
 array([[ 1.1807312],
        [-0.9027189]], dtype=float32),
 array([-0.25268388], dtype=float32)]

In [93]:
xor.predict(x)

array([[0.39589787],
       [0.5993921 ],
       [0.47303775],
       [0.530678  ]], dtype=float32)

**Deep Neural Network to Predict hand written Digit Recognition**

In [94]:
## importing dataset

from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()

In [95]:
print(Data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [96]:
features = Data.data
target = Data.target

print(features.shape)
print(target.shape)

(569, 30)
(569,)


In [97]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(455, 30)
(455,)
(114, 30)
(114,)


In [98]:
from keras.models import Sequential
from keras.layers import Dense

In [99]:
model = Sequential()
model.add(Dense(32, input_dim = 30, activation='relu'))  ##hidden layer 1
model.add(Dense(64, activation='relu'))  ##hidden layer 2
model.add(Dense(1, activation='sigmoid')) 

In [100]:
model.compile(loss='binary_crossentropy' , optimizer='adam', metrics=['accuracy'])

In [101]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 32)                992       
_________________________________________________________________
dense_8 (Dense)              (None, 64)                2112      
_________________________________________________________________
dense_9 (Dense)              (None, 1)                 65        
Total params: 3,169
Trainable params: 3,169
Non-trainable params: 0
_________________________________________________________________


In [102]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 1s 2ms/step - loss: 22.4191 - accuracy: 0.4812
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 2.1408 - accuracy: 0.6011
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.9955 - accuracy: 0.7400
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5382 - accuracy: 0.8213
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6997 - accuracy: 0.8115
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3603 - accuracy: 0.8995
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2807 - accuracy: 0.9027
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3026 - accuracy: 0.9116
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3156 - accuracy: 0.8975
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3639 - accuracy: 0.8610


In [103]:
scores = model.evaluate(X_test, y_test)
print(scores)  ## returns loss and accuracy

4/4 [==============================] - 0s 3ms/step - loss: 0.2152 - accuracy: 0.9298
[0.2152090221643448, 0.9298245906829834]


In [104]:
predictions = model.predict(X_test)
label=[]
for pred in predictions:
   if pred>=0.5:
       print("Malignent")
   else:
       print("Benign")

Benign
Malignent
Malignent
Benign
Malignent
Benign
Benign
Benign
Benign
Benign
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Benign
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Benign
Malignent
Benign
Benign
Benign
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Malignent
Benign
Malignent
Benign
Malignent
Benign
Malignent
Malignent
Malignent
Malignent
Malignent
Malignent
M